### ISSUE TITLE
egui feature will not work if default plugin sets exit_condition

### ISSUE THREAD

**Issue by ybyygu** [Plonq/bevy_panorbit_camera#14]
Thank you for your great work and continuous improvement! I find bevy_egui to be a great feature that I really needed. However, I noticed that it doesn’t work as expected when I set the exit_condition in DefaultPlugins.

Relevant code snippets:

    let default_plugin = DefaultPlugins.set(WindowPlugin {
        // FIXME: it will work if comment below line
        exit_condition: bevy::window::ExitCondition::OnPrimaryClosed,
        ..default()
    });

    App::new()
        .add_plugins(default_plugin)
        .add_plugin(PanOrbitCameraPlugin)
        .add_plugin(WorldInspectorPlugin::default())
        .add_startup_system(setup)
        .run();`

To reproduce this bug
1. Changes I made in my fork:
https://github.com/Plonq/bevy_panorbit_camera/compare/master...ybyygu:bevy_panorbit_camera-egui-bug:master
2. run
    > cargo run --example egui --features bevy_egui

**Comment by Plonq** [comment]
Hi! Thanks for the kind words, and thanks for the bug report. I've got a fix for this incoming.

**Comment by Plonq** [comment]
This should be fixed in v0.4.2

**Comment by ybyygu** [comment]
I appreciate your quick solution to the problem. It works as expected. However, there is a catch: the order of plugins matters. It doesn't work if PanOrbitCameraPlugin comes before WorldInspectorPlugin.

    App::new()
        .add_plugins(default_plugin)
        // FIXME: the plugin order matters
        .add_plugin(PanOrbitCameraPlugin)
        .add_plugin(WorldInspectorPlugin::default())
        .add_startup_system(setup)
        .run();

Check my codes to reproduce:
https://github.com/Plonq/bevy_panorbit_camera/compare/master...ybyygu:bevy_panorbit_camera-egui-bug:master

**Comment by Plonq** [comment]
Released a fix for the plugin ordering issue. Hopefully there are no more issues now, but if there are let me know! Thanks for reporting!
