### ISSUE TITLE
Orbit function without having to press down a key.

### ISSUE THREAD

**Issue by AndrewCS149** [Plonq/bevy_panorbit_camera#24]
Is it possible to have the orbit feature always active and not have to hold down a button?

**Comment by AndrewCS149** [comment]
Ah I see. I was going to try and use this as a third person camera plugin.

**Comment by Plonq** [comment]
Yeah I don't think it's suitable for that use. There are other plugins that are more designed for that use case. https://github.com/BlackPhlox/bevy_config_cam for example (though I just noticed it is still on Bevy 0.7). Maybe you can look at its code.

Third person and first person cameras are tightly coupled with the character controller, which is probably why you don't really see any 'plug and play' plugins for these.

**Comment by Plonq** [comment]
Actually check out https://github.com/AndrewCS149/bevy_third_person_camera - it was just released

**Comment by AndrewCS149** [comment]
@Plonq I am the author :) haha

**Comment by Plonq** [comment]
> @Plonq I am the author of that :) haha

How did I miss that 🤣

**Comment by Plonq** [comment]
Closing this (wontfix)
