### ISSUE TITLE
Latitudinal rotation behaves unexpectedly when allow_upside_down is on

### ISSUE THREAD

**Issue by ybyygu** [Plonq/bevy_panorbit_camera#28]
https://github.com/Plonq/bevy_panorbit_camera/assets/128990/35ca07a4-7978-4995-9207-092b4590081c

For the example `basic`,  I can rotate the plane along the longitudinal axis, but not the latitudinal one. How can I fix this?

How to achieve out of plane rotation instead of in-plane rotation when allow_upside_down?

**Comment by ybyygu** [comment]
I made a temporary fix in this [commit](https://github.com/ybyygu/bevy_panorbit_camera-egui-bug/compare/Plonq:bevy_panorbit_camera:master...master). But it breaks the `allow_upside_down` feature.

**Comment by Plonq** [comment]
This is a camera controller that allows rotating a camera around an object. It only supports 2 axes of rotation, so not all angles are possible. Adding a third axis makes controlling it too difficult - a mouse has only 2 axes of control.

Your commit just makes rotation chaotic and hard to control.

It sounds like this plugin is not going to be suitable for what you want.

**Comment by ybyygu** [comment]
The commit works for me. But it is a dirty hack and will break other features.

https://github.com/Plonq/bevy_panorbit_camera/assets/128990/40567dfc-9dd9-4ff9-b3d0-865925ae5aa5

**Comment by Plonq** [comment]
Maybe we have different definitions of "works". Because to me, this is not acceptable:


https://github.com/Plonq/bevy_panorbit_camera/assets/7709415/cf7549d1-d437-461e-8813-b5ed89b72031

**Comment by ybyygu** [comment]
I appreciate your clarification. I got your point. I'm seeking a more optimal solution.

**Comment by Plonq** [comment]
If you need to control all 3 axes, then you're better off rotating the object instead of moving the camera. Like this: https://draw.plonq.org

**Comment by Plonq** [comment]
I should be clear - I don't think this is the plugin for you. I don't think it makes sense to change this plugin to support 3 axes, because of the complexity that comes with that. I don't even know of a solution that works. Blender has this same "problem".

**Comment by ybyygu** [comment]
> 



> If you need to control all 3 axes, then you're better off rotating the object instead of moving the camera. Like this: https://draw.plonq.org

Thanks for the tip. I will give it a try.
