### ISSUE TITLE
Export EguiWantsFocus resource

### ISSUE THREAD

**Issue by lalomartins** [Plonq/bevy_panorbit_camera#37]
The check for GUI focus is super useful, and I need to do the same for other game input, so I ended up copy-pasting it into my input handling plugin. It would be great if the crate could `pub` it instead, so that I don't have to have two copies of the system and the resource on every frame.

Thanks for the great crate! Not only it works well, but oddly, it uses almost the exact same controls I had in my previous (Godot) prototype. Great minds I guess.

**Comment by Plonq** [comment]
Hey, I'm glad you like this plugin. I don't see any harm re-exporting this, though it should probably be its own plugin if I'm honest. Anyway, I've published 0.9.1 with this change.

**Comment by lalomartins** [comment]
Maybe, or maybe contributed to bevy-egui 🤔
