### ISSUE TITLE
feat: touchscreen controls

### ISSUE THREAD

**Issue by mosure** [Plonq/bevy_panorbit_camera#40]
adding support for touchscreen controls would be great for mobile platforms:

https://github.com/d-bucur/bevy_touch_camera/blob/1bf9bcbdd85c834ffd5eae967f0187535374e8b7/src/plugin.rs#L102

**Comment by Plonq** [comment]
Thanks for the suggestion, I'll look into it when I can.

**Comment by Plonq** [comment]
Released in version 0.11.1
