### ISSUE TITLE
cannot freely rotate around in vertical direction

### ISSUE THREAD

**Issue by ybyygu** [Plonq/bevy_panorbit_camera#6]
I'm using this crate for molecule visualization in  [my project](https://github.com/ybyygu/gchemol-view) and I find it very helpful. Thank you for creating it!

I've encountered an issue that's titled. When I rotate in horizontal direction, it seems to be okay. I'm not sure if it's a feature or a bug.

This can be reproduced in example `basic`:
> cargo run --example basic

**Comment by Plonq** [comment]
Hi @ybyygu! Glad you find it useful.

If I understand correctly, you are saying that you can't make the camera go upside down. There is a configuration for this, called `allow_upside_down`, which is `false` by default. Setting this to true should solve your issue. The [advanced](https://github.com/Plonq/bevy_panorbit_camera/blob/master/examples/advanced.rs) example shows how to set this option.

Can you confirm if this works for you? If not, could you record a video of the issue?

**Comment by ybyygu** [comment]
I tried your solution with configuration `allow_upside_down`, but it is still not working as I expected.

When I repeatly rotate the molecule to the upside or the downside, the molecule cannot be rotated further. But if I rotate to the left or the right, it  works.

[Screencast from 2023-04-25 12-46-12.webm](https://user-images.githubusercontent.com/128990/234179774-a3ba4ac6-425c-434b-bb11-03b3c38232e2.webm)

**Comment by ybyygu** [comment]
Sorry, I just tried your `advanced` example. It works. I am trying to fix the issue in my codes.

**Comment by ybyygu** [comment]
This issue is solve if I set `allow_upside_down` to true. Thank for your great work!
