### ISSUE TITLE
Zoom in the direction of the mouse position

### ISSUE THREAD

**Issue by thmxv** [Plonq/bevy_panorbit_camera#63]
It would be nice to allow zooming in the mouse position and thus not changing what is under the mouse while zooming and having a much more instinctive navigation in the scene.

**Comment by thmxv** [comment]
Relative to this one, I implemented something that does that. 
[gist](https://gist.github.com/thmxv/df97131e3c72089e29bb9fb5f3ab727e)

This code is based on the camera example from the cheat book.

However this was part of a camera controller that was supposed to allow switching between orbit and fly mode and between perspective and orthographic camera but none of this was working/implemented. Also it only works with one window and one viewport.

Still working on how to implement something like this is this addon.

**Comment by Plonq** [comment]
Thanks I'll have a look when I can.

**Comment by thmxv** [comment]
The code is not very good but understandable. I read it once more to understand (I suffered a accident with brain hemorrhage and lost the memories of a few months before and after the accident).

Basically the code does this:

- It does not store the `focus` point, just the `radius` (`target depth` in my code). Because the focus point is always in the direction the camera is pointing to, at the given depth; this is data redundant and must be avoided because it will be a source of issues or bug.
- When zooming, the camera is moved in the direction of the ray calculated based on the mouse position and the `radius` (`target depth`) is reduced/increased depending if it is a zoom in our zoom out operation.
- The camera is moved by a certain `distance` and the `radius` (`target depth`) is reduced/increased by the same distance. But it would be better to do some linear algebra (dot product between 2 vectors from the camera origin, one pointing forward in the middle and one pointing in the mouse cursor direction) to calculate a multiplication factor and apply this factor to the `distance` before adding/subtracting it from the `radius` (`target depth`) so that the focus stays in the same plane (a plane perpendicular to a vector going from the camera origin the the original `focus`)
- No smoothing

Unfortunately, as I understand, this is pretty much incompatible with the way this add-on is implemented and would require a rewrite of some sort which would brake the API.

**Comment by Plonq** [comment]
>Unfortunately, as I understand, this is pretty much incompatible with the way this add-on is implemented and would require a rewrite of some sort which could brake the API.

Yeah I think the fact I calculate the transform every frame based on those 4 values means it's limited in what is possible or practical. But it has many benefits, like making it easy to control the camera manually simply by manipulating those values - putting it in the exact spot you want. Smoothing is also easier.
Blender does it so it must be possible, although Blender's camera isn't smoothed so maybe it's not practical with smoothing.
