### ISSUE TITLE
The multiple_windows examples crashes after closing a window

### ISSUE THREAD

**Issue by thmxv** [Plonq/bevy_panorbit_camera#65]
This affects both the `egui_multiple_windows` and `multiple_windows` examples.  The applications do not crashes directly when closing a window, but after when trying to navigating in the window that was not closed.

**Comment by Plonq** [comment]
Embarrassing 🤣 

![image](https://github.com/Plonq/bevy_panorbit_camera/assets/7709415/904c3457-2cdc-496a-a42c-1fe9a8a85dbb)
