### ISSUE TITLE
Panning in XZ, but not Y direction

### ISSUE THREAD

**Issue by martinbaer** [Plonq/bevy_panorbit_camera#67]
Is it possible to use this plugin to have the camera pan in the X and Y (edit: Z) direction only but not the Z (edit: Y)? This is to make the equivalent of what google earth does where clicking and dragging only moves you horizontally but keeps your altitude the same.

Thanks!

Edit: I meant the XZ (horizontal) plane

**Comment by Plonq** [comment]
It's sort of possible, but you have to disable orbiting entirely by setting the alpha and beta limits to 0. This will lock the camera pointing forward (-Z) and thus panning can only happen in the XY plane.

If you want to allow orbiting though, then that's not currently possible. I'll have a look into adding this functionality, but it sounds like you don't really want an orbit camera at all. Perhaps https://github.com/Plonq/bevy_rts_camera could be suitable? If you want height/altitude to stay consistent then bevy_rts_camera might need some updates to make the automatic altitude optional, but it might be a better fit for what you're trying to do.

**Comment by Plonq** [comment]
Is this what you mean? (Assuming the camera starts pointing roughly in the -Z direction)

https://github.com/Plonq/bevy_panorbit_camera/assets/7709415/c7f29573-f240-4036-a792-74c9ab196105

**Comment by thmxv** [comment]
I suppose he meant the "usual/correct XY plane" or "the horizontal plane" which in Bevy is the XZ plane. Why does artistic 3D packages (minus Blender) and game engine get this differently than every math book or engineering/CAD package is an enigma until the end of time.

**Comment by Plonq** [comment]
My comments above also apply to XZ plane - you can limit alpha/beta to specific values.

>Why does artistic 3D packages (minus Blender) and game engine get this differently than every math book or engineering/CAD package is an enigma until the end of time.

You might find this interesting: https://github.com/bevyengine/bevy/discussions/10488

**Comment by martinbaer** [comment]
Cheers for the help.

I still do want orbiting camera, I just want the Y translation of the camera to be affected only by zooming, not by panning. I'm trying to make a height map of terrain where despite looking at terrain at a pitch angle, you can still click and drag to move horizontally along the terrain like google earth/similar height map tools.

My issue with bevy_rts_camera for my use is that you don't get as much control as this crate, for example the pitch is automatically changed by the zoom, not manually with input. Another bonus is that this crate has click and drag panning. 

So would be great to have a XZ-only panning feature in this crate if it's something that's easily doable and would benefit others.

**Comment by thmxv** [comment]
I suppose making this in a generic way with additional options "lock_pan_x" "lock_pan_y" and "lock_pan_z" is doable and usefull for some. But I am not the owner of this addon and do not know if adding this to the code makes sense or if it is doable externally with a system undoing the move in the vertical axis after the camera controller system and before the render system.

> You might find this interesting: https://github.com/bevyengine/bevy/discussions/10488

I had to post a [response](https://github.com/bevyengine/bevy/discussions/10488#discussioncomment-8780643) to this non-sense.

**Comment by Plonq** [comment]
> My issue with bevy_rts_camera for my use is that you don't get as much control as this crate, for example the pitch is automatically changed by the zoom, not manually with input. Another bonus is that this crate has click and drag panning.

What if it had both those features though? I don't think limiting the pan plane makes much sense in an orbit plugin. You're essentially trying to make an orbit camera act like an rts camera 😆
