### ISSUE TITLE
Rename `(target_)alpha` to `(target_)yaw` and `(target_)beta` to `(target_)pitch`

### ISSUE THREAD

**Issue by thmxv** [Plonq/bevy_panorbit_camera#68]
This would brake the API compatibility and require a code change by the users of this add-on. But better soon than later. Also it would make those parameters roles more explicit and less easy to confuse one by the other.

**Comment by Plonq** [comment]
Hmm you're the second person to complain about alpha/beta naming. FWIW I took the names from [BabylonJS's Arc Rotate camera](https://doc.babylonjs.com/features/featuresDeepDive/cameras/camera_introduction#arc-rotate-camera) (not that I'm arguing BabylonJS is perfect).

I understand the criticism though, and I'm happy to change them.
