### ISSUE TITLE
Jitter with orthographic camera

### ISSUE THREAD

**Issue by thmxv** [Plonq/bevy_panorbit_camera#77]
Since commit 11b0348bccb1187ed29759cb073330ba73520ec5 (pull request #76) there are jitters when in orthographic camera.

To fix this, the system set does not only need to be before `TransformSystem::TransformPropagate` but also before `CameraUpdateSystem` (I think).

**Comment by Plonq** [comment]
Thanks for the report. I couldn't replicate a jitter, but I did notice a subtle flicker on startup which the above change fixes.

Fix in 0.18.2

**Comment by thmxv** [comment]
Yes sorry. I did not express myself well.

The jitters are a bit random depending on system ordering and only while zooming an orthographic camera.

The "I think" came because adding the `.before(CameraUpdateSystem)` fixed the issue for me, but I am not certain this is the correct fix or if it only made the randomness more favorable to me.

**Comment by Plonq** [comment]
Yeah I assumed it was due to random system ordering :D
