### ISSUE TITLE
Tags, releases, and changelog are missing `v0.19.0` and `v0.19.1`

### ISSUE THREAD

**Issue by StudioLE** [Plonq/bevy_panorbit_camera#80]
The latest version according to crates.io is `v0.19.1` but this is not reflected in:
- [ ] [CHANGELOG.md](https://github.com/Plonq/bevy_panorbit_camera/blob/master/CHANGELOG.md)
- [ ] [GitHub Releases](https://github.com/Plonq/bevy_panorbit_camera/releases)
- [ ] [Git Tags](https://github.com/Plonq/bevy_panorbit_camera/tags)

**Comment by Plonq** [comment]
Thanks for reminder. I've updated the change log. I am no longer doing GitHub releases, and therefore release tags, as I don't see much benefit.

**Comment by Plonq** [comment]
Points taken, you convinced me, and thanks for the links. I'll keep up the GH versions/tags.
