### ISSUE TITLE
Add motion to change the rotation center

### ISSUE THREAD

**Issue by valeratrades** [Plonq/bevy_panorbit_camera#83]

**Comment by Plonq** [comment]
Hi, can you please elaborate?

**Comment by valeratrades** [comment]
Ah yes, sorry:

By default the focus_target is fixed at `Vec3::ZERO`, would be great to have a built-in motion to update it to wherever the cursor is pointing, say (simplified)
```rs
if let Some(ray) = window.cursor_position()
		.and_then(|cursor| camera.viewport_to_world(camera_transform, cursor))
	{

		let ray_origin = ray.origin;
		let distance_to_plane = match ray.intersect_plane(Vec3::ZERO, InfinitePlane3d::default()) {
			Some(distance) => distance,
			None => return,
		};
		let new_focus_target = ray_origin + ray.direction * distance_to_plane;
		panorbit.target_focus = new_focus_target; // changes the camera position too, still figuring out how to prevent that
	}
```

Or intersection with the first mesh. And have this say on KeyCode::Space

**Comment by Plonq** [comment]
Thanks for the explanation. It sounds like you want to change the centre of rotation (pivot point) while not affecting  the camera's position/rotation. AKA 'auto depth' in Blender. If that is correct, please see https://github.com/Plonq/bevy_panorbit_camera/issues/64 where this feature was attempted but I ultimately decided it wasn't going to work.
