### ISSUE TITLE
Add hint for disabling panning motion

### ISSUE THREAD

**Issue by 772** [Plonq/bevy_panorbit_camera#88]
I suggest adding the sentence ```A value of 0.0 disables panning motion.``` to [this documentation](https://docs.rs/bevy_panorbit_camera/latest/bevy_panorbit_camera/struct.PanOrbitCamera.html#structfield.pan_sensitivity).

When I wanted to deactivate panning motion, I first checked if button_pan was optional - it isn’t. Then I looked for any boolean to toggle it off - also no. Then, I discovered this value.

Feel free to close this if not agreed. It's just a trivial suggestion.

**Comment by Plonq** [comment]
Thanks for suggestion, I have updated the docs
