### ISSUE TITLE
Light mode

### ISSUE THREAD

**Issue by davids91** [Plonq/bevy_panorbit_camera#92]
Hey! Thank you so much for this awesome lib!! 
 I have some custom rendering logic implemented and would love to use your plugin in my examples. 
 Would it be possible to have a camera deployed, be updated based on input, but without any actual rendering? 

 What I do is I render to a texture, and all I need to do is to display the texture; For that purpose I use the default Camera2D. 
 
 I only need the yaw, pitch and focus data to showcase the rendering logic I implemented; And right now adding a `PanOrbitCamera` is interfering with the camera I am using. 

 Thanks in advance!

**Comment by Plonq** [comment]
Hi there, thanks for the kind words.

Have you checked out [render to texture example](https://github.com/Plonq/bevy_panorbit_camera/blob/master/examples/render_to_texture.rs)? If that doesn't help your situation, could you provide an example of what you're trying to do, and give some more information on how it's interfering?

**Comment by davids91** [comment]
Ah you are right, all it took was: 
```diff
    commands.spawn((
+        Camera {
+            is_active: false,
+            ..default()
+        },
         PanOrbitCamera {
             focus: Vec3::new(0., 300., 0.),
             ..default()
         },
    ));
```
